base: ../base.yaml
attack:
  epsilon: 0.5
  step_size: 0.5
  attack_type: fgsm
  num_steps: 1
  random_start: false
graph:
  k: 150
  topo_k: 150
  use_tangent: false
  tangent_k: 150
  topo_preprocess: none
  topo_min_persistence: 1e-04
detector:
  topo_percentile: 90
  topo_cov_shrinkage: 1e-04
