base: ../base.yaml
attack:
  epsilon: 0.2
  step_size: 0.02
  attack_type: pgd
graph:
  k: 60
  topo_k: 60
  use_tangent: true
  tangent_k: 60
  topo_preprocess: none
  topo_min_persistence: 1e-05
detector:
  topo_percentile: 95
  topo_cov_shrinkage: 0.01
