base: ../base.yaml
attack:
  epsilon: 0.1
  step_size: 0.1
  attack_type: fgsm
  num_steps: 1
  random_start: false
graph:
  k: 40
  topo_k: 40
  use_tangent: true
  tangent_k: 40
  topo_preprocess: pca
  topo_min_persistence: 1e-06
  topo_pca_dim: 32
detector:
  topo_percentile: 95
  topo_cov_shrinkage: 1e-06
