base: ../base.yaml
attack:
  epsilon: 0.05
  step_size: 0.005
  attack_type: pgd
graph:
  k: 40
  topo_k: 40
  use_tangent: false
  tangent_k: 40
  topo_preprocess: pca
  topo_min_persistence: 1e-05
  topo_pca_dim: 10
detector:
  topo_percentile: 90
  topo_cov_shrinkage: 0.01
