base: ../base.yaml
attack:
  epsilon: 0.05
  step_size: 0.05
  attack_type: fgsm
  num_steps: 1
  random_start: false
graph:
  k: 20
  topo_k: 20
  use_tangent: true
  tangent_k: 20
  topo_preprocess: none
  topo_min_persistence: 1e-05
detector:
  topo_percentile: 95
  topo_cov_shrinkage: 0.01
