base: ../base.yaml
attack:
  epsilon: 0.1
  step_size: 0.01
  attack_type: pgd
graph:
  k: 20
  topo_k: 20
  use_tangent: false
  tangent_k: 20
  topo_preprocess: pca
  topo_min_persistence: 1e-06
  topo_pca_dim: 10
detector:
  topo_percentile: 90
  topo_cov_shrinkage: 1e-06
