base: ../base.yaml
attack:
  epsilon: 0.2
  step_size: 0.02
  attack_type: pgd
graph:
  k: 150
  topo_k: 150
  use_tangent: false
  tangent_k: 150
  topo_preprocess: pca
  topo_min_persistence: 1e-05
  topo_pca_dim: 2
detector:
  topo_percentile: 90
  topo_cov_shrinkage: 0.01
