base: ../base.yaml
attack:
  epsilon: 0.3
  step_size: 0.3
  attack_type: fgsm
  num_steps: 1
  random_start: false
graph:
  k: 60
  topo_k: 60
  use_tangent: false
  tangent_k: 60
  topo_preprocess: pca
  topo_min_persistence: 1e-06
  topo_pca_dim: 2
detector:
  topo_percentile: 90
  topo_cov_shrinkage: 1e-06
